{% set name = "netgen" %}
{% set version = "6.2.2007" %}
{% set sha256 = "8ed63d899311644d4f57b7faba79892ce5770fb0cf47ac18048134b996ca709a" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: netgen_v{{ version }}.tar.gz
  url: https://github.com/NGSolve/netgen/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - cmake.patch

build:
  number: 0
  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  host:
    - occt
    - python
    - pybind11
    - zlib
  run:
    - occt
    - python
    - zlib

test:
  commands:
    - python -c "import sys; print(sys.version); import netgen;"

about:
  home: https://sourceforge.net/projects/netgen-mesher/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: this is netgen
  description: NETGEN is an automatic 3d tetrahedral mesh generator. It accepts input from constructive solid geometry (CSG) or boundary representation (BRep) from STL file format. The connection to a geometry kernel allows the handling of IGES and STEP files. NETGEN contains modules for mesh optimization and hierarchical
    mesh refinement. Netgen is open source based on the LGPL license. It is available for Unix/Linux and Windows.
  doc_url: http://www.hpfem.jku.at/netgen/
  dev_url: https://sourceforge.net/projects/netgen-mesher/

extra:
  recipe-maintainers:
    - looooo
