{% set name = "netgen" %}
{% set version = "6.2.1802" %}
{% set sha256 = "01bad9b3f88efc75c46550cb125d824de89debc27abf44abe339e9496e56d261" %}


package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: netgen{{ version }}.tar.gz
    url: https://github.com/NGSolve/netgen/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - python.patch

build:
    number: 0
    skip: true  # [py<35 or win32]


requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        #missing! - {{ cdt('libglu') }}  # [linux]
        - cmake
        - ninja
        - pybind11
    host:
        - occt
        - python
test:
    imports:
        - netgen

about:
    home: https://sourceforge.net/projects/netgen-mesher/
    license: LGPL2.1
    license_family: LGPL
    summary: this is netgen
    description: NETGEN is an automatic 3d tetrahedral mesh generator.
                 It accepts input from constructive solid geometry (CSG) or boundary representation (BRep) from
                 STL file format. The connection to a geometry kernel allows the handling of IGES and STEP files.
                 NETGEN contains modules for mesh optimization and hierarchical mesh refinement.
                 Netgen is open source based on the LGPL license. It is available for Unix/Linux and Windows.
    doc_url: http://www.hpfem.jku.at/netgen/
    dev_url: https://sourceforge.net/projects/netgen-mesher/

extra:
    recipe-maintainers:
        - looooo
